-- MySQL Script generated by MySQL Workbench
-- Wed Apr  8 11:16:00 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema StockPlus
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema StockPlus
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `StockPlus` DEFAULT CHARACTER SET utf8 ;
USE `StockPlus` ;

-- -----------------------------------------------------
-- Table `StockPlus`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE `categoria` (
  `id_categoria` int NOT NULL AUTO_INCREMENT,
  `nome_categoria` varchar(100) NOT NULL,
  `ativo` tinyint DEFAULT '1',
  `data_cadastro` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_categoria`)
) ENGINE=InnoDB;


-- -----------------------------------------------------
-- Table `StockPlus`.`Produtos`
-- -----------------------------------------------------
CREATE TABLE `produtos` (
  `id_produto` int NOT NULL AUTO_INCREMENT,
  `nome_produto` varchar(100) NOT NULL,
  `vinculo_imagem` varchar(255) NOT NULL,
  `id_categoria` int NOT NULL,
  `data_vencimento` date NOT NULL,
  `data_cadastro` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `valor_produto` decimal(10,2) DEFAULT NULL,
  PRIMARY KEY (`id_produto`),
  KEY `fk_Produtos_Categoria1` (`id_categoria`),
  CONSTRAINT `fk_Produtos_Categoria1` FOREIGN KEY (`id_categoria`) REFERENCES `categoria` (`id_categoria`)
) ENGINE=InnoDB;


-- -----------------------------------------------------
-- Table `StockPlus`.`Estoque`
-- -----------------------------------------------------
CREATE TABLE `estoque` (
  `id_estoque` int NOT NULL AUTO_INCREMENT,
  `quantidade` int NOT NULL,
  `quantidade_minima` int NOT NULL,
  `id_produto` int NOT NULL,
  PRIMARY KEY (`id_estoque`),
  KEY `fk_Estoque_Produtos1` (`id_produto`),
  CONSTRAINT `fk_Estoque_Produtos1` FOREIGN KEY (`id_produto`) REFERENCES `produtos` (`id_produto`)
) ENGINE=InnoDB;


-- -----------------------------------------------------
-- Table `StockPlus`.`Pessoas`
-- -----------------------------------------------------
CREATE TABLE `pessoas` (
  `id_pessoa` int NOT NULL AUTO_INCREMENT,
  `nome_pessoa` varchar(100) NOT NULL,
  `email` varchar(150) NOT NULL,
  `tipo` enum('CLIENTE','FORNECEDOR','FUNCIONARIO') NOT NULL,
  PRIMARY KEY (`id_pessoa`)
) ENGINE=InnoDB;


-- -----------------------------------------------------
-- Table `StockPlus`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE `clientes` (
  `id_cliente` int NOT NULL AUTO_INCREMENT,
  `cpf` char(11) NOT NULL,
  `id_pessoa` int NOT NULL,
  PRIMARY KEY (`id_cliente`),
  KEY `fk_Clientes_Pessoa1` (`id_pessoa`),
  CONSTRAINT `fk_Clientes_Pessoa1` FOREIGN KEY (`id_pessoa`) REFERENCES `pessoas` (`id_pessoa`)
) ENGINE=InnoDB;


-- -----------------------------------------------------
-- Table `StockPlus`.`Telefones`
-- -----------------------------------------------------
CREATE TABLE `telefones` (
  `id_telefone` int NOT NULL AUTO_INCREMENT,
  `telefone` char(11) NOT NULL,
  `id_pessoa` int NOT NULL,
  PRIMARY KEY (`id_telefone`),
  KEY `fk_Telefones_Pessoa1` (`id_pessoa`),
  CONSTRAINT `fk_Telefones_Pessoa1` FOREIGN KEY (`id_pessoa`) REFERENCES `pessoas` (`id_pessoa`)
) ENGINE=InnoDB;


-- -----------------------------------------------------
-- Table `StockPlus`.`Pedidos`
-- -----------------------------------------------------
CREATE TABLE `pedidos` (
  `id_pedido` int NOT NULL AUTO_INCREMENT,
  `tipo` enum('COMPRA','VENDA') NOT NULL,
  `valor_total` decimal(10,2) NOT NULL DEFAULT '0.00',
  `data_cadastro` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `id_cliente_fornecedor` int NOT NULL,
  `id_funcionario` int NOT NULL,
  PRIMARY KEY (`id_pedido`),
  KEY `fk_Pedidos_Pessoa1` (`id_cliente_fornecedor`),
  KEY `fk_Pedidos_Pessoa2` (`id_funcionario`),
  CONSTRAINT `fk_Pedidos_Pessoa1` FOREIGN KEY (`id_cliente_fornecedor`) REFERENCES `pessoas` (`id_pessoa`),
  CONSTRAINT `fk_Pedidos_Pessoa2` FOREIGN KEY (`id_funcionario`) REFERENCES `pessoas` (`id_pessoa`)
) ENGINE=InnoDB;


-- -----------------------------------------------------
-- Table `StockPlus`.`ItensPedido`
-- -----------------------------------------------------
CREATE TABLE `itenspedido` (
  `id_itens_pedido` int NOT NULL AUTO_INCREMENT,
  `quantidade` int NOT NULL,
  `status` enum('CONCLUIDO','DEVOLVIDO') NOT NULL,
  `id_pedido` int NOT NULL,
  `id_produto` int NOT NULL,
  `valor_unitario` decimal(10,2) NOT NULL DEFAULT '0.00',
  PRIMARY KEY (`id_itens_pedido`),
  KEY `fk_ItensPedido_Pedidos1` (`id_pedido`),
  KEY `fk_ItensPedido_Produtos1` (`id_produto`),
  CONSTRAINT `fk_ItensPedido_Pedidos1` FOREIGN KEY (`id_pedido`) REFERENCES `pedidos` (`id_pedido`),
  CONSTRAINT `fk_ItensPedido_Produtos1` FOREIGN KEY (`id_produto`) REFERENCES `produtos` (`id_produto`)
) ENGINE=InnoDB;


-- -----------------------------------------------------
-- Table `StockPlus`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE `fornecedor` (
  `id_fornecedor` int NOT NULL AUTO_INCREMENT,
  `cnpj` char(14) NOT NULL,
  `id_pessoa` int NOT NULL,
  PRIMARY KEY (`id_fornecedor`),
  KEY `fk_Fornecedor_Pessoa1` (`id_pessoa`),
  CONSTRAINT `fk_Fornecedor_Pessoa1` FOREIGN KEY (`id_pessoa`) REFERENCES `pessoas` (`id_pessoa`)
) ENGINE=InnoDB;


-- -----------------------------------------------------
-- Table `StockPlus`.`Funcionarios`
-- -----------------------------------------------------
CREATE TABLE `funcionarios` (
  `id_funcionarios` int NOT NULL AUTO_INCREMENT,
  `cargo` varchar(50) NOT NULL,
  `data_admissao` date NOT NULL,
  `id_pessoa` int NOT NULL,
  PRIMARY KEY (`id_funcionarios`),
  KEY `fk_Funcionarios_Pessoa1` (`id_pessoa`),
  CONSTRAINT `fk_Funcionarios_Pessoa1` FOREIGN KEY (`id_pessoa`) REFERENCES `pessoas` (`id_pessoa`)
) ENGINE=InnoDB;

-- -----------------------------------------------------
-- Table `StockPlus`.`Login`
-- -----------------------------------------------------
CREATE TABLE `login` (
  `id_login` int NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL,
  `password_hash` varchar(60) NOT NULL,
  `id_func` int NOT NULL,
  PRIMARY KEY (`id_login`),
  UNIQUE KEY `username` (`username`),
  UNIQUE KEY `id_func` (`id_func`),
  CONSTRAINT `fk_login_funcionario` FOREIGN KEY (`id_func`) REFERENCES `funcionarios` (`id_funcionarios`)
) ENGINE=InnoDB;

-- -----------------------------------------------------
-- Table `StockPlus`.`movimentacoes`
-- -----------------------------------------------------
CREATE TABLE `movimentacoes` (
  `id_movimentacao` int NOT NULL AUTO_INCREMENT,
  `quantidade` int NOT NULL,
  `data_cadastro` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` enum('entrada','saida') NOT NULL,
  `id_itens_pedido` int NOT NULL,
  PRIMARY KEY (`id_movimentacao`),
  KEY `fk_Movimentacoes_ItensPedido1` (`id_itens_pedido`),
  CONSTRAINT `fk_Movimentacoes_ItensPedido1` FOREIGN KEY (`id_itens_pedido`) REFERENCES `itenspedido` (`id_itens_pedido`)
) ENGINE=InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
